name: Release

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

env:
  CARGO_TERM_COLOR: always # GH action logs supports terminal colors

jobs:
  publish:
    name: Build, release, and upload artifacts
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: Swatinem/rust-cache@v2
        with:
          shared-key: cybercmd
          cache-on-failure: true
      - run: cargo xtask dist
      - env:
          GH_TOKEN: ${{ github.token }}
        run: gh release create ${{  github.ref_name }} --generate-notes $(Resolve-Path -Relative -Path ./target/dist/*.zip)
